services:
    redis-server:
        image: 'redis'
        volume:
            - ./redis:/usr/app
        command: ["redis-server","--save","1 1", "--protected-mode", "no"]
    node-app:
        build: ./
        image: docker.io/Sirisha0507/visits
        ports:
            - '8081:8081'